name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: docker run -v "${{ github.workspace }}:C:\Source" ghcr.io/enlyze/wdk710-build-environment powershell \Source\build_on_ci.ps1

    - name: Upload AMD64 binaries
      uses: actions/upload-artifact@v3
      with:
        name: ENLYZE-PortSniffer-amd64
        path: redist_AMD64\*

    - name: Upload x86 binaries
      uses: actions/upload-artifact@v3
      with:
        name: ENLYZE-PortSniffer-x86
        path: redist_x86\*
